import NextAuth from "next-auth";
import CredentialsProvider from "next-auth/providers/credentials";
import { PrismaAdapter } from "@auth/prisma-adapter";
import { prisma } from "./prisma";
import bcrypt from "bcryptjs";
import { z } from "zod";

export const {
    handlers: { GET, POST },
    auth,
    signIn,
    signOut,
} = NextAuth({
    adapter: PrismaAdapter(prisma),
    session: {
        strategy: "jwt",
        maxAge: 30 * 24 * 60 * 60, // 30 days
    },
    pages: {
        signIn: "/login",
        error: "/login",
    },
    providers: [
        CredentialsProvider({
            name: "Credentials",
            credentials: {
                email: { label: "Email", type: "email" },
                password: { label: "Password", type: "password" },
            },
            async authorize(credentials, req) {
                const parsedCredentials = z
                    .object({ email: z.string().email(), password: z.string().min(6) })
                    .safeParse(credentials);

                if (!parsedCredentials.success) {
                    return null;
                }

                const { email, password } = parsedCredentials.data;

                const user = await prisma.user.findUnique({
                    where: { email },
                    include: { role: true },
                });

                if (!user || user.status !== "active") {
                    return null;
                }

                const passwordsMatch = await bcrypt.compare(password, user.password);

                if (!passwordsMatch) {
                    return null;
                }

                // Return user to be encoded into the JWT
                return {
                    id: user.id,
                    name: user.name,
                    email: user.email,
                    image: user.image,
                    roleId: user.roleId,
                    role: user.role.name,
                };
            },
        }),
    ],
    callbacks: {
        async jwt({ token, user, account, trigger, session }) {
            if (user) {
                // Initial sign-in
                token.id = user.id;
                token.roleId = user.roleId;
                token.role = user.role;

                // Create a DB session so we can track and revoke it
                // Note: the JWT payload 'jti' (JWT ID) is usually automatically generated by NextAuth
                // But nextauth v5 doesn't always expose it here inside `jwt` unless we assign it.
                if (!token.jti) {
                    token.jti = crypto.randomUUID();
                }

                // We can create a session in the DB asynchronously
                // using the token's jti so we can revoke this specific token later
                try {
                    await prisma.session.create({
                        data: {
                            userId: user.id as string,
                            type: "jwt",
                            token: token.jti as string,
                            device: "Unknown", // Can be parsed from User-Agent in authorize callback or middleware
                            expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
                        },
                    });
                } catch (e) {
                    console.error("Failed to create session record", e);
                }
            }

            // Check if token was revoked
            if (token.jti) {
                // We shouldn't do a DB call on EVERY request inside the JWT callback
                // for performance. Instead, middleware should check caching or we only check periodically.
                // For strict revocation, we check here:
                const sessionRecord = await prisma.session.findUnique({
                    where: { token: token.jti as string },
                    select: { revoked: true },
                });

                if (!sessionRecord || sessionRecord.revoked) {
                    // Token matches a revoked session or is deleted
                    throw new Error("Session is revoked");
                }
            }

            return token;
        },
        async session({ session, token }) {
            if (token && session.user) {
                session.user.id = token.id as string;
                session.user.roleId = token.roleId as string;
                session.user.role = token.role as string;
            }
            return session;
        },
    },
});
